19:49:36.078 ERROR  Task was destroyed but it is pending!
task: <Task pending name='Task-13' coro=<WebSocketCommonProtocol.close_connection() done, defined at /home/obukowski/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py:1271> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6f66c735b0>()]>>
19:56:11.161 ERROR   $$ ----- KeyError(('action', 'response', 'time', 'type')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('action', 'response', 'time', 'type')
19:56:11.162 ERROR   $$ ----- KeyError(('action', 'response', 'time', 'type')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('action', 'response', 'time', 'type')
19:56:11.162 ERROR   $$ ----- KeyError(('action', 'response', 'time', 'type')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('action', 'response', 'time', 'type')
19:56:11.162 ERROR   $$ ----- KeyError(('action', 'response', 'time', 'type')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('action', 'response', 'time', 'type')
19:56:11.162 ERROR   $$ ----- KeyError(('action', 'response', 'time', 'type')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('action', 'response', 'time', 'type')
19:56:11.163 ERROR   $$ ----- KeyError(('action', 'response', 'time', 'type')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('action', 'response', 'time', 'type')
19:56:11.163 ERROR   $$ ----- KeyError(('action', 'response', 'time', 'type')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('action', 'response', 'time', 'type')
19:56:11.163 ERROR   $$ ----- KeyError(('action', 'response', 'time', 'type')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('action', 'response', 'time', 'type')
19:56:11.163 ERROR   $$ ----- KeyError(('action', 'response', 'time', 'type')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('action', 'response', 'time', 'type')
19:56:11.163 ERROR   $$ ----- KeyError(('action', 'response', 'time', 'type')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('action', 'response', 'time', 'type')
19:56:11.410 ERROR   $$ ----- KeyError(('action', 'response', 'time', 'type')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('action', 'response', 'time', 'type')
19:56:11.410 ERROR   $$ ----- KeyError(('action', 'response', 'time', 'type')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('action', 'response', 'time', 'type')
19:56:11.411 ERROR   $$ ----- KeyError(('action', 'response', 'time', 'type')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('action', 'response', 'time', 'type')
19:56:11.411 ERROR   $$ ----- KeyError(('action', 'response', 'time', 'type')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('action', 'response', 'time', 'type')
19:56:11.411 ERROR   $$ ----- KeyError(('action', 'response', 'time', 'type')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('action', 'response', 'time', 'type')
19:56:13.869 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:13.902 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:15.199 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:15.813 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:16.429 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:16.429 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:16.429 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:16.429 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:16.430 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:16.430 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:16.430 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:16.430 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:16.430 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:16.430 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:16.431 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:16.431 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:16.431 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:16.431 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:16.431 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:20.114 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:20.114 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:20.605 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:22.881 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:22.881 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:24.981 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:27.021 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:27.021 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:27.050 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:28.101 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:29.330 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:29.331 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:29.331 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:29.945 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:31.006 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:36.498 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:36.498 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:36.498 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:36.499 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:36.499 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:36.499 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:36.499 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:36.499 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:36.500 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:36.500 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:36.500 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:36.500 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:36.500 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:36.501 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:36.501 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:37.626 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:38.136 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:38.755 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:38.755 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:38.755 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:39.263 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:40.389 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:41.825 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:44.752 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:46.328 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:51.143 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:52.882 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:53.408 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:54.430 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:54.471 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:55.442 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:56:56.338 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:56.338 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:56.338 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:56.346 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:56.347 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:56.347 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:56.347 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:56.347 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:56.348 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:56.348 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:56.348 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:56.349 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:56.349 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:56.349 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:56:56.349 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:02.098 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:08.344 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:10.801 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:15.309 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:16.362 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:16.363 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:16.367 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:16.367 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:16.367 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:16.368 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:16.368 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:16.368 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:16.368 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:16.371 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:16.371 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:16.371 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:16.372 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:16.372 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:16.372 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:17.560 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:24.524 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:24.524 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:24.525 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:24.525 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:27.014 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:30.432 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:30.522 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:30.554 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:30.575 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:31.149 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:31.169 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:31.208 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:31.217 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:31.241 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:31.302 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:35.275 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:36.399 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:36.399 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:36.399 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:36.400 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:36.400 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:36.400 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:36.400 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:36.401 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:36.401 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:36.401 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:36.401 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:36.402 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:36.402 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:36.402 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:36.402 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:36.811 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:41.112 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:41.933 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:42.443 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:42.956 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:46.297 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:50.433 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:51.250 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:52.528 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:55.408 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:57:56.406 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:56.406 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:56.407 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:56.407 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:56.407 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:56.407 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:56.408 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:56.408 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:56.410 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:56.414 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:56.414 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:56.414 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:56.414 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:56.415 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:56.415 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:57:59.239 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:03.026 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:03.075 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:04.870 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:04.870 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:04.870 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:04.870 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:07.741 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:07.742 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:09.170 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:09.229 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:09.289 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:09.306 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:09.356 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:09.391 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:09.681 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:09.989 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:09.989 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:10.159 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:10.812 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:11.832 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:12.485 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:14.292 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:14.293 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:16.543 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:16.543 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:16.544 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:16.544 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:16.544 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:16.545 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:16.545 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:16.545 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:16.545 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:16.545 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:16.545 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:16.545 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:16.546 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:16.546 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:16.546 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:16.546 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:16.546 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:16.547 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:16.575 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:17.361 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:17.978 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:17.978 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:18.493 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:18.493 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:24.529 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:24.939 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:24.940 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:25.554 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:27.909 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:28.728 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:29.447 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:30.573 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:32.517 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:32.556 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:32.606 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:32.927 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:34.137 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:36.615 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:36.615 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:36.616 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:36.616 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:36.616 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:36.616 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:36.616 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:36.617 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:36.617 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:36.617 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:36.617 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:36.617 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:36.617 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:36.617 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:36.618 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:39.275 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:40.299 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:42.554 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:43.271 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:43.884 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:43.884 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:44.498 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:45.010 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:47.877 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:50.744 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:51.558 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:51.802 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:56.481 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:56.481 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:56.481 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:56.481 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:56.481 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:56.482 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:56.482 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:56.482 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:56.482 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:56.482 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:56.482 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:56.482 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:56.485 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:56.485 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:56.485 ERROR   $$ ----- KeyError(('type',)) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type',)
19:58:56.821 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:58.936 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:58:59.851 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
19:59:00.599 ERROR   $$ ----- KeyError(('type', 'book', 'payload')) $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 138, in main
    socket_class.response_mapping(tuple(list(response.keys())), response)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_trades.py", line 71, in response_mapping
    return mapping_dict[response_keys_tuple](response)
KeyError: ('type', 'book', 'payload')
08:03:19.866 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=aave_usd') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=aave_usd')
08:03:20.000 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=mana_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=mana_mxn')
08:03:20.199 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=link_usd') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=link_usd')
08:03:20.426 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn')
08:03:20.613 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn')
08:03:20.760 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_mxn')
08:03:20.962 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn')
08:03:21.204 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn')
08:03:21.385 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn')
08:03:21.913 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_brl') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_brl')
08:03:22.135 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn')
08:03:22.338 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=ltc_usd') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=ltc_usd')
08:03:22.510 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=mana_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=mana_mxn')
08:03:22.749 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn')
08:03:22.988 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=mana_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=mana_mxn')
08:03:23.183 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn')
08:03:23.384 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn')
08:03:23.718 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_mxn')
08:03:23.891 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn')
08:03:24.084 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=ltc_usd') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=ltc_usd')
08:03:24.261 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_mxn')
08:03:24.450 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_brl') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_brl')
08:03:24.647 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_mxn')
08:03:24.882 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_brl') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_brl')
08:03:25.170 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn')
08:03:25.395 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_mxn')
08:03:25.807 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn')
08:03:26.076 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn')
08:03:26.251 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn')
08:03:26.452 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_brl') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_brl')
08:03:26.698 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn')
08:03:26.911 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_mxn')
08:03:27.104 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn')
08:03:27.275 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn')
08:03:27.517 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn')
08:03:27.800 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=mana_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=mana_mxn')
08:03:28.050 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn')
08:03:28.284 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=link_usd') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=link_usd')
08:03:28.499 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=mana_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=mana_mxn')
08:03:28.733 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn')
08:03:28.947 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_mxn')
08:03:29.132 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_mxn')
08:03:29.306 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn')
08:03:29.498 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=ltc_usd') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=ltc_usd')
08:03:29.687 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn')
08:03:29.940 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn')
08:03:30.228 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn')
08:03:30.508 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn')
08:03:30.784 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn')
08:03:31.160 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn')
08:03:31.297 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=btc_mxn')
08:03:31.488 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn')
08:03:32.074 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn')
08:03:32.205 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn')
08:03:32.661 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=link_usd') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=link_usd')
08:03:33.119 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn')
08:03:33.287 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=ltc_usd') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=ltc_usd')
08:03:33.617 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=sand_usd') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=sand_usd')
08:03:33.916 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=ftm_usd') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=ftm_usd')
08:03:34.302 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=aave_usd') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=aave_usd')
08:03:34.688 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_mxn')
08:03:35.463 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn')
08:03:35.666 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_usd') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=xrp_usd')
08:03:35.808 ERROR   $$ 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn') $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 62, in main
    responses = await asyncio.gather(*tasks)
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 22, in single_url_getter
    message = await response.json()
  File "/home/obukowski/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.bitso.com/v3/order_book/?book=eth_mxn')
08:03:36.187 ERROR   $$ Connection kill, error:  $$ 
Traceback (most recent call last):
  File "/home/obukowski/Desktop/hft_algo/db_ex_connections/bitso/bitso_ob.py", line 136, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
